// frontend/src/lib/components/nodes/InputNode.svelte
<script lang="ts">
	import { Handle, Position } from '@xyflow/svelte';
	import type { NodeProps } from '@xyflow/svelte';
	import { MessageSquare } from 'lucide-svelte';

	let { data }: NodeProps = $props();

	let query = $state((data?.query as string) || 'What is the capital of France?');

	function updateQuery(e: Event) {
		const target = e.target as HTMLTextAreaElement;
		query = target.value;
		data.query = query;
	}

</script>

<div class="sentinel-node input-node">
	<div class="node-header">
		<MessageSquare size={18} class="node-icon" strokeWidth={2} />
		<span class="node-title">Input</span>
	</div>
	<div class="node-body">
		<textarea
			value={query}
			oninput={updateQuery}
			class="sentinel-input text-sm w-full min-h-16 resize-y nodrag nopan"
			placeholder="Enter your prompt..."
		></textarea>
	</div>
	<Handle type="source" position={Position.Bottom} />
</div>

// frontend/src/components/nodes/InputNode.tsx
import { useState } from 'react';
import { Handle, Position } from '@xyflow/react';
import type { NodeProps } from '@xyflow/react';
import { MessageSquare, X } from 'lucide-react';
import { useCanvasStore } from '../../stores/canvasStore';

function InputNode({ data, id }: NodeProps) {
	const { updateNode, removeNode } = useCanvasStore();
	const [query, setQuery] = useState<string>((data?.query as string) || 'What is the capital of France?');

	const handleQueryChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
		const newQuery = e.target.value;
		setQuery(newQuery);
		updateNode(id, { query: newQuery });
	};

	const handleDelete = (e: React.MouseEvent) => {
		e.stopPropagation();
		removeNode(id);
	};

	return (
		<div className="sentinel-node input-node">
			<button className="node-delete-btn nodrag nopan" onClick={handleDelete} title="Delete node">
				<X size={10} strokeWidth={2} />
			</button>
			<div className="node-header">
				<MessageSquare size={18} className="node-icon" strokeWidth={2} />
				<span className="node-title">Input</span>
			</div>
			<div className="node-body">
				<textarea
					value={query}
					onChange={handleQueryChange}
					className="sentinel-input text-[0.65rem] w-full min-h-16 resize-y nodrag nopan"
					placeholder="Enter your prompt..."
				/>
			</div>
			<Handle type="source" position={Position.Bottom} />
		</div>
	);
}

export default InputNode;
