// frontend/src/lib/components/nodes/ToolNode.svelte
<script lang="ts">
	import { Handle, Position } from '@xyflow/svelte';
	import type { NodeProps } from '@xyflow/svelte';
	import { Wrench, X } from 'lucide-svelte';
	import { nodesStore, edgesStore } from '$lib/stores/canvas';

	let { data, id }: NodeProps = $props();

	let toolName = $state(data.toolName || 'web_search');
	let toolDescription = $state(data.toolDescription || '');

	function updateToolName(e: Event) {
		const target = e.target as HTMLInputElement;
		toolName = target.value;
		data.toolName = toolName;

		// Trigger store update for reactivity
		nodesStore.update(nodes =>
			nodes.map(n => n.id === id ? { ...n, data: { ...n.data, toolName } } : n)
		);
	}

	function updateToolDescription(e: Event) {
		const target = e.target as HTMLTextAreaElement;
		toolDescription = target.value;
		data.toolDescription = toolDescription;

		// Trigger store update for reactivity
		nodesStore.update(nodes =>
			nodes.map(n => n.id === id ? { ...n, data: { ...n.data, toolDescription } } : n)
		);
	}

	function deleteNode(e: Event) {
		e.stopPropagation();
		nodesStore.update(nodes => nodes.filter(n => n.id !== id));
		edgesStore.update(edges => edges.filter(e => e.source !== id && e.target !== id));
	}
</script>

<div class="sentinel-node tool-node">
	<button class="node-delete-btn nodrag nopan" onclick={deleteNode} title="Delete node">
		<X size={12} strokeWidth={2.5} />
	</button>
	<div class="node-header">
		<Wrench size={18} class="node-icon" strokeWidth={2} />
		<span class="node-title">Tool</span>
	</div>
	<div class="node-body">
		<div class="space-y-3">
			<div class="nodrag nopan">
				<label for="tool-name" class="label">Tool Name</label>
				<input
					id="tool-name"
					type="text"
					value={toolName}
					oninput={updateToolName}
					class="sentinel-input text-[0.65rem] w-full nodrag nopan"
					placeholder="e.g. web_search"
				/>
			</div>
			<div class="nodrag nopan">
				<label for="tool-description" class="label">Description</label>
				<textarea
					id="tool-description"
					value={toolDescription}
					oninput={updateToolDescription}
					class="sentinel-input text-[0.65rem] w-full min-h-16 resize-y nodrag nopan"
					placeholder="Tool description..."
				></textarea>
			</div>
		</div>
	</div>
	<Handle type="target" position={Position.Top} />
	<Handle type="source" position={Position.Bottom} />
</div>

// frontend/src/components/nodes/ToolNode.tsx
import { useState } from 'react';
import { Handle, Position } from '@xyflow/react';
import type { NodeProps } from '@xyflow/react';
import { Wrench, X } from 'lucide-react';
import { useCanvasStore } from '../../stores/canvasStore';

function ToolNode({ data, id }: NodeProps) {
	const { updateNode, removeNode } = useCanvasStore();
	const [toolName, setToolName] = useState<string>((data?.toolName as string) || 'web_search');
	const [toolDescription, setToolDescription] = useState<string>((data?.toolDescription as string) || '');

	const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const newName = e.target.value;
		setToolName(newName);
		updateNode(id, { toolName: newName });
	};

	const handleDescriptionChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
		const newDesc = e.target.value;
		setToolDescription(newDesc);
		updateNode(id, { toolDescription: newDesc });
	};

	const handleDelete = (e: React.MouseEvent) => {
		e.stopPropagation();
		removeNode(id);
	};

	return (
		<div className="sentinel-node tool-node">
			<button className="node-delete-btn nodrag nopan" onClick={handleDelete} title="Delete node">
				<X size={10} strokeWidth={2} />
			</button>
			<div className="node-header">
				<Wrench size={18} className="node-icon" strokeWidth={2} />
				<span className="node-title">Tool</span>
			</div>
			<div className="node-body">
				<div className="space-y-3">
					<div className="nodrag nopan">
						<label htmlFor="tool-name" className="label">Tool Name</label>
						<input
							id="tool-name"
							type="text"
							value={toolName}
							onChange={handleNameChange}
							className="sentinel-input text-[0.65rem] w-full nodrag nopan"
							placeholder="e.g. web_search"
						/>
					</div>
					<div className="nodrag nopan">
						<label htmlFor="tool-description" className="label">Description</label>
						<textarea
							id="tool-description"
							value={toolDescription}
							onChange={handleDescriptionChange}
							className="sentinel-input text-[0.65rem] w-full min-h-16 resize-y nodrag nopan"
							placeholder="Tool description..."
						/>
					</div>
				</div>
			</div>
			<Handle type="target" position={Position.Top} />
			<Handle type="source" position={Position.Bottom} />
		</div>
	);
}

export default ToolNode;
